[package]
name = "solana-bpf-rust-param-passing-dep"
version = "1.14.20"
description = "Solana BPF program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-rust-param-passing-dep"
edition = "2021"

[dependencies]
solomka-program = { path = "../../../../sdk/program", version = "=1.14.20" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
