[package]
name = "solomka-client-test"
version = "1.14.20"
description = "Solomka RPC Test"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/pavlo-u/solomka-chain"
license = "Apache-2.0"
documentation = "https://docs.rs/solana-client-test"
edition = "2021"
publish = false

[dependencies]
futures-util = "0.3.21"
serde_json = "1.0.81"
serial_test = "0.8.0"
solomka-client = { path = "../client", version = "=1.14.20" }
solana-ledger = { path = "../ledger", version = "=1.14.20" }
solana-measure = { path = "../measure", version = "=1.14.20" }
solana-merkle-tree = { path = "../merkle-tree", version = "=1.14.20" }
solana-metrics = { path = "../metrics", version = "=1.14.20" }
solana-perf = { path = "../perf", version = "=1.14.20" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.14.20" }
solana-rpc = { path = "../rpc", version = "=1.14.20" }
solana-runtime = { path = "../runtime", version = "=1.14.20" }
solomka-sdk= { path = "../sdk", version = "=1.14.20" }
solana-streamer = { path = "../streamer", version = "=1.14.20" }
solana-test-validator = { path = "../test-validator", version = "=1.14.20" }
solana-transaction-status = { path = "../transaction-status", version = "=1.14.20" }
solana-version = { path = "../version", version = "=1.14.20" }
systemstat = "0.1.11"
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]
solana-logger = { path = "../logger", version = "=1.14.20" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
