[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.14.20"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-watchtower"

[dependencies]
clap = "2.33.1"
humantime = "2.0.1"
log = "0.4.17"
solomka-clap-utils = { path = "../clap-utils", version = "=1.14.20" }
solomka-cli-config = { path = "../cli-config", version = "=1.14.20" }
solomka-cli-output = { path = "../cli-output", version = "=1.14.20" }
solomka-client = { path = "../client", version = "=1.14.20" }
solana-logger = { path = "../logger", version = "=1.14.20" }
solana-metrics = { path = "../metrics", version = "=1.14.20" }
solana-notifier = { path = "../notifier", version = "=1.14.20" }
solomka-sdk= { path = "../sdk", version = "=1.14.20" }
solana-version = { path = "../version", version = "=1.14.20" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
