[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.14.20"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.1.6"
ctrlc = { version = "3.2.2", features = ["termination"] }
indexmap = "1.9.1"
indicatif = "0.16.2"
pickledb = { version = "0.5.1", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
solomka-account-decoder = { path = "../account-decoder", version = "=1.14.20" }
solomka-clap-utils = { path = "../clap-utils", version = "=1.14.20" }
solomka-cli-config = { path = "../cli-config", version = "=1.14.20" }
solomka-client = { path = "../client", version = "=1.14.20" }
solomka-remote-wallet = { path = "../remote-wallet", version = "=1.14.20" }
solomka-sdk= { path = "../sdk", version = "=1.14.20" }
solana-transaction-status = { path = "../transaction-status", version = "=1.14.20" }
solana-version = { path = "../version", version = "=1.14.20" }
spl-associated-token-account = { version = "=1.1.3" }
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
tempfile = "3.4.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
solana-logger = { path = "../logger", version = "=1.14.20" }
solana-streamer = { path = "../streamer", version = "=1.14.20" }
solana-test-validator = { path = "../test-validator", version = "=1.14.20" }
